# ====== Customized Configuration ======
# Place your personal settings here.
# These will overwrite values from config_default.yaml.
# Focus on tuning here — check config_default.yaml for parameter full descriptions.

# Note that you can create your own config_XXXXX.yaml and assign it to script by
# adding this arguments: --cfg XXXXX
# -----------------------------------------

# 🎯 KEY BINDINGS
# Match these to your in-game keys. Uncomment once you're done.
key:
  aoe_skill: "s"            # 💥 Set to the AoE skill key. Choose a key with low cooldown.
  directional_attack: "d"   # ⚔️ Assign to your main spammable attack.
  teleport: ""             # 🌀 Leave empty ("") if your class can’t teleport.
  jump: "z"             # 🦘 Set to jump. No need to change unless you use a non-standard key.
  add_hp: "1"               # ❤️ Assign to HP potion hotkey. Match with your potion shortcut.
  add_mp: "2"               # 💧 Assign to MP potion hotkey. Match with your potion shortcut.

# ────────────────
# 🌀 Mage Teleport
# ────────────────
# This feature lets Mages use teleport to move faster while walking.
# ⚠️ Still experimental! Enabling it may cause route-following issues.

teleport:
  is_use_teleport_to_walk: False  # ✅ Use teleport while walking (may cause inaccurate pathing)
  cooldown: 1                     # ⏱️ Teleport skill cooldown (in seconds)

# ────────────────
# 🧙‍♂️ Edge Teleport
# ────────────────
# When your character approaches the edge of a platform,
# this feature triggers a teleport (for Mages) to prevent falling.
# If your character isn't a Mage, it will perform a jump instead.

edge_teleport:
  enable: False                 # ✅ Enable or disable this feature
  trigger_box_width: 20        # ↔️ Width of the edge detection box (in pixels)
  trigger_box_height: 10       # ↕️ Height of the edge detection box (in pixels)
  color_code: [255, 127, 127]  # 🎨 RGB color code to represent platform edge


# 🧙 BUFF SKILLS
# Add keys for buffs you want to auto-cast. Match cooldowns with actual in-game durations.
buff_skill:
  keys: ["f"]          # ⌨️ Add one or more buff keys here (in order).
  cooldown: [122]       # ⏱️ Set each skill’s cooldown (seconds). Be precise to avoid spamming.

# ⚔️ DIRECTIONAL ATTACK SETTINGS
# Tune these by observing the debug window.
# Smaller range -> you will fight monster in close-range combat
# Larger range -> you will attack monster far away, but could hit nothing if it's set to large
directional_attack:
  range_x: 320              # ↔️ Try reducing if you’re hitting unreachable monsters.
  range_y: 60               # ↕️

# 💥 AOE SKILL SETTINGS
# Similar to directional attack. Adjust to match your AoE hitbox on screen.
aoe_skill:
  # Multiple heal
  # range_x: 350               # ↔️ Try reducing if you’re hitting unreachable monsters.
  # range_y: 170               # ↕️
  # Holy light
  range_x: 400               # ↔️ Try reducing if you’re hitting unreachable monsters.
  range_y: 170               # ↕️

# ❤️ HEALTH MONITOR
# Use this to auto-drink potions at specific HP/MP thresholds.
# Cleric use skill to heal; therefore, need to set force_heal to False
health_monitor:
  enable: True              # ✅ Set to False if using pet auto-heal.
  force_heal: False          # 🛡️ Heal first — stop attacking until HP is restored
  add_hp_ratio: 0.5         # ❤️ drink potion when HP is below this number
  add_mp_ratio: 0.5         # 💙 drink potion when MP is below this number


# ────────────────
# ⚠️ Rune Warning Detection
# ────────────────
# Detects the "Please remove the rune" message on screen.
# When this warning appears, the bot will pause combat and start searching for the rune instead.
rune_warning:
  top_left: [513, 216]        # 🟦 Top-left corner of the rune warning message
  bottom_right: [768, 256]    # 🟥 Bottom-right corner of the rune warning
  diff_thres: 0.2             # 📏 Matching threshold [0.0 ~ 1.0], higher = stricter match

rune_solver:
  arrow_box_size: 80           # 📐 Arrow icon size in pixels (e.g., 75x75 box)
  arrow_box_interval: 170      # ↔️ Distance between arrows (horizontal spacing in pixels)
  arrow_box_coord: [355, 365]  # 🎯 Top-left coordinate of the first (leftmost) arrow
  arrow_box_diff_thres: 0.32    # 📏 Match threshold [0.0 ~ 1.0]
                               #     ↪ If the match score of the first arrow is lower than this,
                               #     the solver assumes the rune mini-game has start

# ────────────────
# ⚙️ System Settings
# ────────────────
# Controls performance and behavior of core system threads.

system:
  fps_limit_main: 30                # 🚥 Main loop FPS – controls how fast the main thread runs
  fps_limit_keyboard_controller: 30 # 🚥 Keyboard controller thread FPS
  fps_limit_window_capturor: 20     # 🚥 Window capture thread FPS
  fps_limit_route_recorder: 10      # 🚥 Route recorder FPS
  fps_limit_auto_dice_roller: 1     # 🚥 Auto rice roller FPS
  key_debounce_interval: 1          # ⏱️ Cooldown (in seconds) between function key presses (e.g., F1, F2...)
  show_debug_window: True           # 🐞 Show debug window (disable to save resources)
  server: "TW"                      # "TW", "NA"
  language: "chinese"               # "english" "chinese"
